# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1baIFgV3QZMK62IZAVVzmZ44DCVLTYX9p
"""

print("ola mundo")

print("Andre Messias, São Paulo")

filme = input("Informe o nome do seu filme favorito : ")
ano = input("Informe o ano em que o filme foi lançado: ")
print("O filme " + filme + " foi lançado em " + ano)

numero1 = float(input("Digite o primeiro número: "))
numero2 = float(input("Digite o segundo número: "))

soma      = (numero1 + numero2)
subtracao = (numero1 - numero2)
produto   = (numero1 * numero2)
divisao   = (numero1 / numero2)

print("Soma = " , soma)
print("Subtração = " , subtracao)
print("Multiplicação = " , produto)
print("Divisão = " , divisao)

temperatura = int(input("Digite a temperatura atual"))
if temperatura > 30 :
  print("Esta quente")
elif temperatura <15 :
  print("Esta frio")
else:
  print("Temperatura Agradável")

for i in range(1,11):
  if i % 2 == 0:
    print (i)

#Crie um programa que pergunte ao usuário por números até que ele digite zero e
#então mostre a soma dos números digitados.
soma = 0
numero = int(input("Digite um número para continuar ou 0 para encerrar: " ))
while numero != 0:
 soma += numero
 numero = int(input("Digite um número para continuar ou 0 para encerrar: "))
print("A soma dos números digitados é:", soma)

#Crie uma lista de compras que permita ao usuário adicionar itens e, em seguida,
#imprimir a lista completa.

listaDeCompras = []

itemDeCompra = input("Digite o nome do item da compra para continuar ou X para encerrar: ")

while(itemDeCompra != 'X' and itemDeCompra != 'x'):
  listaDeCompras.append(itemDeCompra)
  itemDeCompra = input("Digite o nome do item da compra para continuar ou X para encerrar: ")


listaCompleta =""
for listaDeCompras in listaDeCompras:
 listaCompleta += listaDeCompras + " "
print(listaCompleta)

#Escreva uma função que receba um número e retorne se ele é par ou ímpar
def parOuImpar(numero):
  if(numero % 2 == 0):
    print("Par")
  else:
    print("Impar")

parOuImpar(3)

#Escreva um programa que peça uma frase ao usuário e conte quantas vezes uma letra
#específica aparece

frase = input("Digite uma frase: ")

letra = input("Digite a letra que deseja contar: ")

contador = frase.count(letra)

print("Quantidade que a letra aparece: ", contador)

#Crie um programa que encontre e imprima todos os números primos em um intervalo
#definido pelo usuário.
def eh_primo(numero):
    if numero < 2:
        return False
    for i in range(2, int(numero ** 0.5) + 1):
        if numero % i == 0:
            return False
    return True


inicio = int(input("Digite o valor inicial do intervalo: "))
fim = int(input("Digite o valor final do intervalo: "))


print(f"Números primos entre {inicio} e {fim}:")
for numero in range(inicio, fim + 1):
    if eh_primo(numero):
        print(numero)

